language: cpp
sudo: false
dist: trusty
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xutils-dev
      - g++-7
      - gcc-7

before_install:
  - set -e
  - pyenv global 2.7.14
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh
  - mkdir $HOME/cmake
  - sh cmake.sh --skip-license --exclude-subdir --prefix=$HOME/cmake
  - export PATH="$HOME/cmake/bin:$PATH"
 
install:
  - set -e
  - pip install conan --user
  - python remotes.py

script:
  - set -e
  - if [[ "${CC}" == "gcc" ]]; then export CC=gcc-7; export CXX=g++-7; fi
  - mkdir build
  - conan install -if build . --build
  - conan build -bf build .
