language: cpp
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt update -qq
  - sudo apt install -y g++-7 gcc-7 xutils-dev
  - pyenv global 2.7.14
  - sudo rm $(which cmake)
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
 
install:
  - if [[ "${EVAL}" != "" ]]; then eval "${EVAL}"; fi
  - pip install conan --user
  - python remotes.py
  - mkdir build
  - conan install -if build . --build

script:
  - if [[ "${EVAL}" != "" ]]; then eval "${EVAL}"; fi
  - conan build -bf build .

env:
  - EVAL="CC=gcc-7 && CXX=g++-7"