language: cpp
compiler:
  - gcc
  - clang
install: >
  sudo apt update -qq &&
  sudo apt install -qq unzip libssl1.0.0 openssl &&
  wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh &&
  sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local &&
  sudo pip install conan && python remotes.py
script: make