language: cpp
compiler:
  - gcc
  - clang
install: >
  wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh &&
  sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local &&
  sudo pip install conan &&
  python remotes.py &&
  sudo apt install -qq unzip
script: make